# Generated by Django 5.0.6 on 2024-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoprojectweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.CharField(default='youremail@somewhere.net', max_length=200),
        ),
    ]
